const PropertyActionTypes = {
    FETCH_PROPERTIES_START: 'FETCH_PROPERTIES_START',
    FETCH_PROPERTIES_SUCCESS: 'FETCH_PROPERTIES_SUCCESS',
    FETCH_PROPERTIES_FAILURE: 'FETCH_PROPERTIES_FAILURE'
};

export default PropertyActionTypes;
